export const cities = [
  "Kabal",
  "Kablar",
  "Kačkovec",
  "Kadanovci",
  "Kadina Glavica",
  "Kadumi",
  "Kajgana",
  "Kajini",
  "Kakanj",
  "Kakinac",
  "Kakma",
  "Kalac",
  "Kaldanija",
  "Kaldir",
  "Kaldrma",
  "Kalebovac",
  "Kalenić",
  "Kali",
  "Kalić",
  "Kalina",
  "Kalinovac",
  "Kalinovača",
  "Kalinovica",
  "Kalinje",
  "Kalnik",
  "Kaluđerovac",
  "Kalje",
  "Kamanje",
  "Kamen",
  "Kamena Gorica",
  "Kamenac",
  "Kamenci",
  "Kamenica",
  "Kamenica",
  "Kamenica",
  "Kamenica Skradnička",
  "Kamenički Vrhovec",
  "Kameničko Podgorje",
  "Kamenmost",
  "Kamenska",
  "Kamenski Hrib",
  "Kamenski Šeovci",
  "Kamenski Vučjak",
  "Kamensko",
  "Kamensko",
  "Kamensko",
  "Kamenjak",
  "Kamešnica",
  "Kampelje",
  "Kampor",
  "Kanegra",
  "Kanfanar",
  "Kaniška Iva",
  "Kaniža",
  "Kaniža",
  "Kaniža Gospićka",
  "Kantrovci",
  "Kanjane",
  "Kaočine",
  "Kapela",
  "Kapela",
  "Kapela Dvor",
  "Kapela Kalnička",
  "Kapela Korenička",
  "Kapela Ravenska",
  "Kapelec",
  "Kapelica",
  "Kapelica",
  "Kapelna",
  "Kapelski Vrh",
  "Kapelščak",
  "Kapetanovo Polje",
  "Kapinci",
  "Kapljuv",
  "Kapovići",
  "Kaprije",
  "Kaptol",
  "Karadžićevo",
  "Karakašica",
  "Karalić",
  "Karanac",
  "Karane",
  "Karasi",
  "Karigador",
  "Karivaroš",
  "Karlobag",
  "Karlovac",
  "Karlovac Feričanački",
  "Karlovec Ludbreški",
  "Karlovići",
  "Karojba",
  "Kartalije",
  "Kastav",
  "Kasuni",
  "Kašćerga",
  "Kašić",
  "Kašina",
  "Kašinska Sopnica",
  "Kašljavac",
  "Kašt",
  "Kaštel",
  "Kaštel Dežanovački",
  "Kaštel Gomilica",
  "Kaštel Kambelovac",
  "Kaštel Lukšić",
  "Kaštel Novi",
  "Kaštel Stari",
  "Kaštel Sućurac",
  "Kaštel Štafilić",
  "Kaštel Žegarski",
  "Kaštelanec",
  "Kaštelir",
  "Katinac",
  "Katinka",
  "Katinovac",
  "Katoličke Čaire",
  "Katoličko Selišće",
  "Katoro",
  "Katun",
  "Katun",
  "Katuni",
  "Kavran",
  "Kavrani",
  "Kebel",
  "Kegljevac",
  "Kejići",
  "Kekići",
  "Kelemen",
  "Keleminovec",
  "Kelešinka",
  "Kenđelovec",
  "Kepčije",
  "Kerestinec",
  "Keseri",
  "Keserov Potok",
  "Kestenovac",
  "Kestenovac",
  "Kestenjak",
  "Kestenje",
  "Kešinci",
  "Kičeri",
  "Kihalac",
  "Kijani",
  "Kijevo",
  "Kik",
  "Kindrovo",
  "Kinjačka",
  "Kip",
  "Kirin",
  "Kirmenjak",
  "Kistanje",
  "Kitišanci",
  "Klada",
  "Kladare",
  "Kladari",
  "Kladešćica",
  "Kladje",
  "Kladnik",
  "Kladnjice",
  "Klakar",
  "Klake",
  "Klana",
  "Klanac",
  "Klanac",
  "Klanac",
  "Klanac Perjasički",
  "Klanice",
  "Klanjec",
  "Klanječno",
  "Klarići",
  "Klarići",
  "Klašnjica",
  "Klek",
  "Klenice",
  "Klenovac",
  "Klenovec Humski",
  "Klenovica",
  "Klenovnik",
  "Klenovščak",
  "Klepeće Selo",
  "Kletište",
  "Kličevica",
  "Klimen",
  "Klimni",
  "Klimno",
  "Klinac",
  "Klinča Sela",
  "Klipino Brdo",
  "Klis",
  "Klisa",
  "Klisa",
  "Klisa",
  "Kliševo",
  "Klobučak",
  "Klokoč",
  "Klokočevac",
  "Klokočevac Samoborski",
  "Klokočevci",
  "Klokočevik",
  "Klokovec",
  "Kloštar",
  "Kloštar Ivanić",
  "Kloštar Podravski",
  "Kloštar Šiljevički",
  "Kloštar Vojakovački",
  "Klupci",
  "Klupica",
  "Kljaić Brdo",
  "Kljake",
  "Kljenak",
  "Ključ",
  "Ključ",
  "Ključ Brdovečki",
  "Ključar",
  "Ključić Brdo",
  "Kmeti",
  "Knapić",
  "Knapići",
  "Knez Gorica",
  "Knezovec",
  "Knezovljani",
  "Knežci",
  "Kneževac",
  "Kneževi Vinogradi",
  "Knežević Kosa",
  "Kneževo",
  "Knežica",
  "Knin",
  "Kninsko Polje",
  "Kobasičari",
  "Kobilić",
  "Kobilić Pokupski",
  "Kobiljača",
  "Kobiljak",
  "Kocijani",
  "Kočičin",
  "Kočići",
  "Kohanjac",
  "Kokanj",
  "Kokinac",
  "Kokirevo",
  "Kokočak",
  "Kokorić",
  "Kolan",
  "Kolarec",
  "Kolarevo Selo",
  "Kolarić",
  "Kolarina",
  "Kolarovec",
  "Kolašac",
  "Koledinec",
  "Kolenica",
  "Kolenovac",
  "Koločep",
  "Kolumbera",
  "Koljane",
  "Kom",
  "Komaji",
  "Komarna",
  "Komarnica",
  "Komarnica Ludbreška",
  "Komarovci",
  "Komatnica",
  "Komazeci",
  "Komesarac",
  "Kometnik-Jorgići",
  "Kometnik-Zubići",
  "Komić",
  "Komin",
  "Komin",
  "Komiža",
  "Komlenići",
  "Komletinci",
  "Komogovina",
  "Komolac",
  "Komor Začretski",
  "Komora",
  "Komorica",
  "Kompanj",
  "Kompator",
  "Kompolje",
  "Kompolje Koreničko",
  "Komuševac",
  "Komušina",
  "Konak",
  "Končanica",
  "Končarev Kraj",
  "Kondrić",
  "Konšćani",
  "Konšćica",
  "Konštari",
  "Kontešići",
  "Konjarić Vrh",
  "Konjevrate",
  "Konjkovsko",
  "Konjsko",
  "Konjsko",
  "Konjsko Brdo",
  "Konjščina",
  "Kopačevo",
  "Kopčevec",
  "Koprivna",
  "Koprivna",
  "Koprivnica",
  "Koprivnica",
  "Koprivnica Zagorska",
  "Koprivnički Bregi",
  "Koprivnički Ivanec",
  "Koprivno",
  "Koprno",
  "Korana",
  "Korana",
  "Koranska Strana",
  "Koranski Brijeg",
  "Koranski Lug",
  "Koransko Selo",
  "Korčula",
  "Kordići Žumberački",
  "Kordunski Ljeskovac",
  "Korduševci",
  "Korelići",
  "Korenica",
  "Koreničani",
  "Korenić Brdo",
  "Korenići",
  "Korenjak",
  "Koretinec",
  "Korija",
  "Korita",
  "Korita",
  "Korita",
  "Korita Rakovička",
  "Koritinja",
  "Koritna",
  "Koritna",
  "Korlat",
  "Korlevići",
  "Kornati",
  "Kornić",
  "Korog",
  "Koromačno",
  "Koromani",
  "Korušce",
  "Kosa",
  "Kosa Janjačka",
  "Kosavin",
  "Kosi",
  "Kosijer Selo",
  "Kosijersko Selo",
  "Kosinožići",
  "Kosinjski Bakovac",
  "Kosna",
  "Kosore",
  "Kosoriga",
  "Kosovac",
  "Kosovečko",
  "Kostadinovac",
  "Kostanj",
  "Kostanje",
  "Kostanjevac",
  "Kostanjevac",
  "Kostanjevec Podvrški",
  "Kostanjevec Podvrški",
  "Kostanjevec Riječki",
  "Kostanjica",
  "Kostel",
  "Kostel Pribićki",
  "Kostelsko",
  "Kostelj",
  "Kostrčani",
  "Kostrena Sveta Barbara",
  "Kostrena Sveta Lucija",
  "Kostreši Bjelovački",
  "Kostreši Šaški",
  "Kostrići",
  "Koška",
  "Koškovec",
  "Košljun",
  "Košnica",
  "Košutarica",
  "Košute",
  "Košutići",
  "Kotarani",
  "Kotari",
  "Kotarice",
  "Kotelja",
  "Kotezi",
  "Kotezi",
  "Kotlenice",
  "Kotli",
  "Kotlina",
  "Kotor",
  "Kotoriba",
  "Koturić",
  "Koturić",
  "Kovačevac",
  "Kovačevac",
  "Kovačevac",
  "Kovači",
  "Kovačić",
  "Kozalj Vrh",
  "Kozaperovica",
  "Kozarac",
  "Kozarac",
  "Kozarevac",
  "Kozarevac Račanski",
  "Kozarica",
  "Kozarice",
  "Kozibrod",
  "Kozica",
  "Kozice",
  "Kozinščak",
  "Kozjača",
  "Kozjak",
  "Kozjak Začretski",
  "Kozjan",
  "Kozji Vrh",
  "Kozlikovo",
  "Kožino",
  "Kožlovac",
  "Kožljak",
  "Kožljani",
  "Kračevec",
  "Kraguj",
  "Kraj",
  "Kraj",
  "Kraj Donji",
  "Kraj Drage",
  "Kraj Gornji -južni dio",
  "Kraj Gornji -sjeverni dio",
  "Krajačići",
  "Krajcar Brijeg",
  "Krajići",
  "Krajiška Kutinica",
  "Krajna",
  "Krajska Vas",
  "Krakar",
  "Kraljev Vrh",
  "Kraljev Vrh",
  "Kraljev Vrh",
  "Kraljeva Velika",
  "Kraljevac",
  "Kraljevac",
  "Kraljevčani",
  "Kraljevec na Sutli",
  "Kraljevec Radobojski",
  "Kraljevec Šemnički",
  "Kraljevica",
  "Kraljevo Selo",
  "Krančići",
  "Krančići",
  "Kranjci",
  "Kranjci",
  "Krapan",
  "Krapanj",
  "Krapina",
  "Krapina Selo",
  "Krapinica",
  "Krapinske Toplice",
  "Krapje",
  "Kras",
  "Kras",
  "Krasica",
  "Krasica",
  "Kraskovići",
  "Krasno",
  "Krašić",
  "Kratečko",
  "Kravarsko",
  "Kravljak",
  "Kravljak",
  "Krbava",
  "Krbavčići",
  "Krbavica",
  "Krbune",
  "Krbune",
  "Krculi",
  "Krč",
  "Krč Bosiljevski",
  "Krčenik",
  "Krčevina",
  "Kreča Ves",
  "Kremenići",
  "Kresini",
  "Kreševo",
  "Kreštelovac",
  "Kričina",
  "Kričke",
  "Kričke",
  "Kričke",
  "Kringa",
  "Krištanovec",
  "Krivac",
  "Krivaj",
  "Krivaj",
  "Krivaj Sunjski",
  "Krivaja",
  "Krivaja Pustara",
  "Krivaja Vojnićka",
  "Krivi Put",
  "Krivodol",
  "Krivodol",
  "Križ",
  "Križ Brdovečki",
  "Križ Gornji",
  "Križ Hrastovački",
  "Križ Kamenica",
  "Križ Koranski",
  "Križanci",
  "Križanče",
  "Križanče",
  "Križančići",
  "Križanec",
  "Križci",
  "Križevci",
  "Križevčec",
  "Križic",
  "Križine",
  "Križišće",
  "Križnica",
  "Križovec",
  "Križovljan",
  "Križovljan Radovečki",
  "Križpolje",
  "Krk",
  "Krkač",
  "Krkanec",
  "Krković",
  "Krkuž",
  "Krmed",
  "Krmpotske Vodice",
  "Krndija",
  "Krneza",
  "Krnežići",
  "Krnica",
  "Krničari",
  "Krnići",
  "Krnjak",
  "Krnjeuve",
  "Kropinjak",
  "Krstatice",
  "Krstinja",
  "Krš",
  "Kršan",
  "Kršanci",
  "Krščenovec",
  "Kršete",
  "Kršikla",
  "Kršinci",
  "Kršuli",
  "Krti",
  "Kruge",
  "Krunčići",
  "Krunoslavje",
  "Krupa",
  "Krupače",
  "Krušak",
  "Kruščica",
  "Kruševica",
  "Kruševo",
  "Kruševo",
  "Kruševo",
  "Kruškovac",
  "Kruškovača",
  "Krušljevac",
  "Krušljevec",
  "Krušljevo Selo",
  "Krušvar",
  "Krušvari",
  "Krvavac I",
  "Krvavac II",
  "Krvavica",
  "Krželji",
  "Kuberton",
  "Kučaj",
  "Kučari",
  "Kuče",
  "Kučeli",
  "Kučer",
  "Kučiće",
  "Kučilovina",
  "Kučine",
  "Kućan Ludbreški",
  "Kućan Marof",
  "Kućanci",
  "Kućanci Đakovački",
  "Kućanec",
  "Kućari",
  "Kućevice",
  "Kućibreg",
  "Kućišta Cesarička",
  "Kućište",
  "Kujići",
  "Kujnik",
  "Kujnik",
  "Kuk",
  "Kukci",
  "Kukljica",
  "Kukljić",
  "Kukuljani",
  "Kukuljanovo",
  "Kukunjevac",
  "Kukurini",
  "Kula",
  "Kula Atlagić",
  "Kula Norinska",
  "Kuljaji",
  "Kuljani",
  "Kumrovec",
  "Kuna Konavoska",
  "Kuna Pelješka",
  "Kunčani",
  "Kunđevec",
  "Kunić",
  "Kunić Ribnički",
  "Kunišinci",
  "Kunovac",
  "Kunovac Kupirovački",
  "Kunovci",
  "Kunovec",
  "Kunovec Breg",
  "Kunj",
  "Kupa",
  "Kupari",
  "Kupčina Žumberačka",
  "Kupeć Dol",
  "Kupina",
  "Kupinec",
  "Kupinečki Kraljevec",
  "Kupinovac",
  "Kupirovo",
  "Kupjak",
  "Kupljenovo",
  "Kupljensko",
  "Kurili",
  "Kurjak",
  "Kurjavići",
  "Kurpezova Gorica",
  "Kuršanec",
  "Kusaja",
  "Kusanovec",
  "Kusijevec",
  "Kusonje",
  "Kustići",
  "Kuševac",
  "Kuštani",
  "Kutanja",
  "Kuterevo",
  "Kutinica",
  "Kutinska Slatina",
  "Kutjevo",
  "Kutnjak",
  "Kutovi",
  "Kuzma",
  "Kuzma Perjasička",
  "Kuzmica",
  "Kuzminec",
  "Kuzminec Miljanski",
  "Kuzminec",
  "Kuželj",
  "Kvarte",
];
